name: Generate minutes list

on: 
  push:
  repository_dispatch:
    types: [minutes]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@master

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: haresfield-pc/minutes
          path: minutes

      - name: Generate minutes list
        uses: 'docker://sixeyed/mdgenerator:latest' 
        env:
          Input__Path: '/github/workspace/minutes'
          Output__Path: '/github/workspace/docs/minutes.md'

      - name: Commit
        run: |          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/minutes.md
          git commit -m "Generated minutes"
          git push