name: Generate downloads list

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@master

      - name: Checkout downloads repo
        uses: actions/checkout@v2
        with:
          repository: haresfield-pc/downloads
          path: downloads

      - name: Generate downloads list
        uses: 'docker://sixeyed/mdgenerator:latest' 
        env:
          Input__Path: '/github/workspace/downloads'
          Input__Filter: '*.*'
          Output__Tile: 'Downloads'
          Output__RepoName: 'haresfield-pc/downloads'
          Output__RepoUrl: 'https://github.com/haresfield-pc/downloads'
          Output__FileBaseUrl: 'https://raw.githubusercontent.com/haresfield-pc/downloads/master'
          Output__Path: '/github/workspace/docs/downloads.md'

      - name: Commit
        run: |          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/downloads.md
          git commit -m "Generated downloads"
          git push